pipeline:
  tests:
    image: python:3.6
    commands:
      - pip install tox
      - tox -e isort
      - tox -e flake8
      - tox -e black

  docker:
    image: plugins/docker
    when:
      branch:
        - master
    repo: abakus/brus
    secrets: [ docker_username, docker_password ]
    tags:
      - ${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7}

  print_receipt:
    image: plugins/webhook
    settings:
        urls: http://gateway.openfaas.svc.cluster.local:8080/function/faas-to-mqtt-relay/
        content_type: application/json
        template: |
            {
                "topic": "printer_as_a_service/print",
                "message": "[{ \"text\": \"Build number: #{{ build.number }}\nBuild status: {{ build.status }}\nComitter: {{ commit.author }}\nCommit message:\n{{ commit.message }}\", \"repo\": \"{{ repo.name }}\" }]"
            }
