---
kind: pipeline
type: docker
name: default

steps:
  - name: steps
    image: python:3.6
    commands:
      - pip install tox
      - tox -e isort
      - tox -e flake8
      - tox -e black

  - name: docker
    image: plugins/docker
    when:
      branch:
        - master
      event: push
      status: success
    settings:
      registry: https://registry.webkom.dev
      repo: registry.webkom.dev/webkom/brus
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - latest
        - ${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7}
