pipeline:
  tests:
    image: python:3.6
    commands:
      - pip install tox
      - tox -e isort
      - tox -e flake8
      - tox -e black

  docker:
    image: plugins/docker
    when:
      branch:
        - master
    registry: https://registry.abakus.no
    repo: registry.abakus.no/webkom/brus
    secrets: [ docker_username, docker_password ]
    tags:
      - latest
      - ${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7}

