[tox]
envlist = isort, flake8, black
skipsdist = True

[testenv]
basepython = python3.6
deps =
    isort: isort
    flake8: flake8
    black: black
commands =
    isort: isort -c -rc brus
    flake8: flake8
    black: black --check brus
