# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-23 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("liste", "0002_auto_20160503_0953")]

    operations = [
        migrations.AlterField(
            model_name="brus", name="cost", field=models.IntegerField(default=16)
        )
    ]
