# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-24 10:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("liste", "0003_auto_20160923_1401")]

    operations = [migrations.DeleteModel(name="Brus")]
