# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-03 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liste', '0005_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='sodasBought',
            field=models.IntegerField(default=0),
        ),
    ]
