# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-12 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liste', '0005_auto_20161114_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
