# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-03 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liste', '0006_person_sodasbought'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sodaBalance', models.IntegerField(default=0)),
                ('sodasBought', models.IntegerField(default=0)),
            ],
        ),
    ]
