# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-04 17:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liste', '0007_brus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brus',
        ),
    ]
